### ISSUE TITLE
Realease APK elsewhere than on Play Store

### ISSUE THREAD

**Issue by NeodarZ** [apognu/otter#1]
Hi

First thanks for your work!

I would like test your app but I don't have a google play account and I don't want to use a version distributed on Play Store anyway. (Yes I know I can use Aurora Store or other app like that but only in last case)

I think I can build a version for my self, but I think it's a better idea, for other people, to put a version on Github release page and, if possible, on F-Droid.

**Comment by apognu** [comment]
That was requested elsewhere and I plan to do it.

At first, I will put up APKs on the release page when I have time to set up CI (maybe this weekend, but no promises). F-Droid might take some more time, while I learn how publishing works there.

**Comment by NeodarZ** [comment]
ok, no problem.

Thank you

**Comment by EliotBerriot** [comment]
@apognu I can help with the CI and testing part if you need :)

**Comment by apognu** [comment]
The latest tag (1.0.12) was also published as an (debug) APK in the Releases section of GitHub. Future releases will also appear there.

Still nothing on F-Droid's side of things, but I will look into it.
