### ISSUE TITLE
I recently upgraded and lost all artwork

### ISSUE THREAD

**Issue by iot-resister** [apognu/otter#105]
**Describe the bug**

**How to reproduce**

**Expected behavior**

using thetarkus all in one container latest yields no  art. There is artwork on  the web frontend. 
**Screenshots**
![](https://i.imgur.com/wlSp2Po.png)

**Environment details**

 - Device:
 - Android version:

happens on tablet, phone and android tv
 - App version:
 - If public Funkwhale instance, its URL:

**Logs**

Add any related logs from ADB or from the "Copy logs" setting.

I couldn't find anything relevant with logcat

**Comment by AMoonRabbit** [comment]
If you haven't already, you might need to clear the app cache. I assume you have updated and 1.0.1 for your Funkwhale instance and run the command to regenerate all thumbnails?

https://docs.funkwhale.audio/changelog.html

Please see the "Increased quality of JPEG thumbnails (manual action required)" section.

**Comment by iot-resister** [comment]
Thanks!
