### ISSUE TITLE
Add a Shuffle Queue functionality

### ISSUE THREAD

**Issue by steevefontaine** [apognu/otter#107]
I think it would be nice to have a button to shuffle the queue.

Currently we can go to a playlist screen and play it randomly (which adds the playlist tracks in a random order to the queue), but we can't add tracks from multiple playlists/albums/artists/search result, then shuffle everything that was added.

**Comment by steevefontaine** [comment]
Actually I had "Randomize" in mind instead of "Shuffle", so I didn't search correctly for previous issues. I found issues #35 and #66 that talk about shuffling the queue. There's a screenshot in #66 with a possible implementation of the Shuffle Queue functionality (and I really like these two new buttons in this screenshot :D) so if it's still in the works, this issue may just be a duplicate of #35 or #66.

**Comment by Thovi98** [comment]
You can try it with the latest develop apk here https://github.com/apognu/otter/releases/download/tip/app-debug.apk. 
Does it fits your need ?

**Comment by steevefontaine** [comment]
> You can try it with the latest develop apk here https://github.com/apognu/otter/releases/download/tip/app-debug.apk.
> Does it fits your need ?

Yes it's exactly what I need, thanks.
