### ISSUE TITLE
App is crashing after login

### ISSUE THREAD

**Issue by EliotBerriot** [apognu/otter#11]
Since the latest update, Otter crashes immediatly after login. When I restart the app, it crashes again. I've tried on two different pods (my pod and the demo server).

Context:

- I'm running [FairPhone OS](https://support.fairphone.com/hc/en-us/articles/208342503) (an Android with Google related stuff removed, based on Android 7.1)
- Otter version: 1.0.13.1000013 (Installed from Aurora Store)

I'm not sure how to troubleshoot this, as I don't see any stack trace or error message, it just crashes, and Android offers to restart it. Let me know what I can do to help pinpoint this!

**Comment by apognu** [comment]
Does it happen on a clean install? Someone else reported something similar in #3 after the fix, but a clean install fixed it. If it does, I'll have to investigate further.

**Comment by EliotBerriot** [comment]
Yes, uninstalling and reinstalling doesn't fix the issue. I've also tried by installing from the APK directly, without success

**Comment by earboxer** [comment]
I'm having the same issue. I'm running OnePlus's OxygenOS (based on Android 7.1.1). I have Google Play Store and Services disabled.

Though I am noting that when launching the app, for a split second I can see the view (showing artists). In the 1.0.12 build, I even briefly saw the artists (from my 0.20.1 funkwhale instance) being listed before the app crashed.

**Comment by apognu** [comment]
Are those public instances where I could create an account?

**Comment by earboxer** [comment]
Mine is public, but without registration. I've emailed you an invite link so you can test it. (Though I'll also note that I tried the app when my server was on funkwhale 0.19.0, and it had the same problem).

**Comment by EliotBerriot** [comment]
> Are those public instances where I could create an account?

I've reproduced this with both https://open.audio (where you can signup freely) and https://funkwhale.eliotberriot.com (my private pod). Is there any crash log I could get to help you troubleshoot this'

**Comment by apognu** [comment]
Sorry about the silence, I'm a bit under load these times.

I was able to reproduce the issue on a 7.1.1 emulator, I will overhaul the faulty code this weekend and try and push an update on the store.

**Comment by EliotBerriot** [comment]
Glad to hear that you found the root cause @apognu. Also you don't have to apologize for having a life outside of this project, really.

Take care!

**Comment by apognu** [comment]
@EliotBerriot, @earboxer: can any of you two test the APK from [1.0.15-rc.1](https://github.com/apognu/otter/releases/tag/1.0.15-rc.1)? It should, from my tests, fix this issue as well as #2.

I will publish it to the Play Store if your tests are successful.

The version code from this APK will be the same as the Play Store release, and you may have to uninstall it before installing it from the store / Aurora.

**Comment by earboxer** [comment]
Yes, it fixes the issue (and seems to work fine from brief testing).

**Comment by EliotBerriot** [comment]
@apognu I confirm it fixes the issue for me as well!

**Comment by apognu** [comment]
Update is published, it should be available soon.
