### ISSUE TITLE
Future Changes in Funkwhale Authentication

### ISSUE THREAD

**Issue by critbase** [apognu/otter#122]
I recently started tracking upstream's develop branch in my funkwhale instance. Because of this, I noticed that there are breaking changes in authentication upstream; specifically, the removal of the `/api/v1/token` and `/api/v1/token/refresh` endpoints.

The relevant commits seem to be these: [Remove JWT related code](https://dev.funkwhale.audio/funkwhale/funkwhale/-/commit/88de997603d4862f92694b0355e2fbfb600b1d4a) and [Remove last JWT related includes](https://dev.funkwhale.audio/funkwhale/funkwhale/-/commit/3231573047c2a5ec4678b6eebae94329147b8836).

This isn't a pressing issue yet; these commits are only in the develop branch, and aren't even present in any release. Still, I feel it's worth being aware of potential breaking changes.

**Comment by georgkrause** [comment]
This seems to be critical to be done when Funkwhale 1.2 is released. But some preparations are already done: https://github.com/apognu/otter/commit/002ebec7ce9bea61beb30f57a038e95fb65353ff

**Comment by Etua** [comment]
I think this issue is a duplicate of #63

**Comment by critbase** [comment]
ah, i missed that. closing in favor of #63
