### ISSUE TITLE
Login optionnal for instance with public music

### ISSUE THREAD

**Issue by arthurlutz** [apognu/otter#14]
It would be great if otter could be used without login/password for funkwhale instances that don't require login to listen to the music (creative commons centered for example https://open.audio/ )

I am personally trying to listen to https://musique.festivalparminous.org/library

**Comment by apognu** [comment]
Thanks for the feedback, I'll try and see what that entails.

**Comment by apognu** [comment]
Hi, and sorry about the long reaction time.

This is now available as a checkbox on the login screen in 1.0.16.
