### ISSUE TITLE
Accept donations

### ISSUE THREAD

**Issue by keunes** [apognu/otter#18]
I am direly waiting until this app supports Chromecast (#16), and I love the idea of a dedicated app for Funkwhale. I am currently preparing a round of donations to a range of different FOSS projects, and I would happily donate to this app to support its further development. Would you, @apognu, be open to receiving donations?

**Comment by timothydlister** [comment]
That would be great. This is by far the best funkwhale mobile client imho. I'd love to donate some beer money in your direction as I'm sure others would too.

**Comment by scizzorz** [comment]
+1

**Comment by apognu** [comment]
Hi everyone,

Sorry about the delay, I had to take care of some personal issues that prevented me from being active on this project, which is exactly the reason why I am not comfortable accepting any donations at this time.

I am really glad that you like this app, thank you! And I will try my best to try and be more reactive in the future.

I will be responding on #16 as soon as I can get any advancement on Chromecast support.

Thanks again. :)

**Comment by apognu** [comment]
So, I managed to get organized enough to contribute regularly to Otter once again, with the healthcare situation slowly going back to normal. I said I would reconsider this once this happened.

Now, I don't have any idea how that works, or what tools one should use. I just know I'm not really comfortable accepting anything crypto-related.

What platform would donors be OK using? GitHub Sponsors? Something like Liberapay? Something else?

**Comment by keunes** [comment]
> What platform would donors be OK using?

Funkwhale & many other projects (I donate to) use [Open Collective](https://opencollective.com/). For me, that'd be perfect. Also, it gives donors insights into what the money is used for (developer renumeration, hosting, conference visits, merch, ...)

> what should people be donating towards? General development of Otter or specific features?

General development IMHO. Otherwise the paying hold power, whereas the developer should have the power ('cause it's still a hobby project, so dev should be fun & based on your interests) with input from wide community (not only those with financial means).

**Comment by apognu** [comment]
I totally agree with your last point, I don't want to have to steer Otter's development towards donating users. I just wanted to check with people.

I only heard about Open Collective (through Funkwhale's message boards), I'll give it a read.

All in all, except for my crypto adversity, I don't really have a personal preference, so I would like to follow a path that most people would be comfortable with.

**Comment by apognu** [comment]
There might be something I am not getting, OpenCollective seems to be made for communities and the whole "payout" mechanism based on invoices and expenses.

In my case, I would not employed by Otter (so, no remuneration perse, and no invoice), and I am very unlikely to have expenses.

Is individual developer backing something that is supported by OpenCollective? I could not find any information about that.

**Comment by apognu** [comment]
I'll check out Liberapay from now, since it seems to have individuals in mind, as opposed to Open Collective. If anyone more information about individuals on Open Collective, I'll reconsider it.

**Comment by apognu** [comment]
Actually, Liberapay only supports Stripe and Paypal, which both leak some personal data (at least email, and even my phone number in Stripe's case). And I guess donors could also be annoyed by that.

I didn't think it would be such a complex subject, to be honnest.

**Comment by keunes** [comment]
> OpenCollective seems to be made for communities and the whole "payout" mechanism based on invoices and expenses

Yeah, that's true. Though it's of course possible to claim money without an invoice, or (as an intermediary option), cash out donations following the implementation of features or releases. I don't think any officially registered organisation or employment status is necessary. But yes, maybe not the best platform ever for your case.

Otherwise, my second-most used method for donations last year was simply direct PayPal transfers (via [PayPal.Me](https://www.paypal.com/fr/smarthelp/article/qu'est-ce-que-paypal.me%C2%A0--faq3025?app=searchAutoComplete)) - [seems to be free](https://www.paypal.com/fr/webapps/mpp/ua/useragreement-full#tableOfFees1). But [GitHub Sponsors](https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/contacting-your-sponsors) also works (for single or regular donations), and allows you to share updates with funders :) Don't know about the payment methods an data that's shared, though.

> I didn't think it would be such a complex subject, to be honnest.

Yeah, can imagine.

**Comment by apognu** [comment]
Thanks for this. Already having a Paypal Account, this way could be easy for me, but I'll also investigate the GitHub Sponsors route, since it seems a bit more integrated into GitHub's workflow. :)

**Comment by apognu** [comment]
And well, if I go ahead and use PayPal, I may as well use Liberapay's PayPal integration too. Probably more fees, but it seems to be appreciated

**Comment by apognu** [comment]
I have been admitted into GitHub Sponsors, I've then added the two platforms we discussed (GitHub Sponsors and PayPal.me) to this repository's sponsorships options. I may add other options in the future if any detail regarding personal data and/or invidivual versus collective changes (wink OpenCollective).

**Comment by popindavibe** [comment]
Well, just discovering this nice Funkwhale client now (will test soon!), but anything Github-related tells me Microsoft, which doesn't really appeal to anything nice I can think of.
Liberapay is a better option for me, even though they cannot process payment directly (they were on Mangopay earlier, but were ditched from that platform later on). Also, I never had issues with Stripes so far (had plenty with Paypal, which I now stay away from as much as I can).

**Comment by apognu** [comment]
I am under the impression that Stripe's integration in Liberapay would display my phone number (requested twice in Stripe's account creation, including as a "support phone number") to anyone who tries to donate to me.

This is non-starter for me. If I am wrong here, and neither my email address nor my phone number are given to a donee, I might reconsider.

I understand people have preferences as far as payment processors go, but I do too, and I will not use something that might disclose something I would like to keep private.

**Comment by popindavibe** [comment]
Liberapay itself will not reveal anything, it is however mentioned on the website that while they anonymize donations, the payment platforms do transpire information:

From https://en.liberapay.com/about/privacy 

> ### Payment processors

>The intermediaries involved in payment processing collect information for anti-fraud purposes, for example the name and IP address of the payer. Please read these documents if you want more information: Stripe's privacy policy and PayPal's privacy policy.
> ### Personal information leaks

> Liberapay does not tell creators who their patrons are. However, PayPal allows the recipient of a payment to see the name and email address of the payer, so donors who don't want to reveal themselves should not choose PayPal as the payment method.

> Similarly, PayPal allows a donor to see the name and email address of the recipient, and Stripe may expose the recipient's phone number, so creators who do not want to reveal their identities should not use these payment processors, unless they have carefully configured their accounts to only leak nonsensitive information (a business name instead of the creator's name, a dedicated email address and phone number instead of the creator's personal contact details).

**Comment by popindavibe** [comment]
So, no perfect solutions as far as I can see.

**Comment by apognu** [comment]
Unfortunately, none that I can see right now.

You can enjoy the app, that's what counts the most. :)
