### ISSUE TITLE
Does not always remember last played position

### ISSUE THREAD

**Issue by grondinm** [apognu/otter#19]
I have experienced this a few times. More so when using Bluetooth.

Connect to Bluetooth headset. Play some music. Pause/Disconnect headset. When headset reconnects some time later the track restarts from the beginning.

Also saw it if otter gets killed in background. Last playing track will start from beginning.

Not sure i am explaining that properly.

**Comment by hdurer** [comment]
Same here.  Pause the play, switch to other apps.  Some time later come back to the app and it has forgotten the play position.
Doesn't happen reliably, never when I try to make it do it.

**Comment by apognu** [comment]
This is expected, as I do not (yet) persist track progress on disk, so this information is lost whenever the app is killed (as opposed to queue state).

This should not be difficult to implement, but I would have to find an acceptable value for this persistence, writing it every second is not something I aspire to.

I'll see what I can do.

**Comment by grondinm** [comment]
I think personally I would be fine with it writing progress when playback is paused. Or if playing over Bluetooth when the Bluetooth connection is killed.

Thank you for looking at this.

May 28, 2020 21:31:12 Antoine POPINEAU <notifications@github.com>:

**Comment by apognu** [comment]
The player would pause anyway if your Bluetooth connection is killed, so yeah, that might be a good solution. Let me investigate this for the next release.

**Comment by apognu** [comment]
This should be fixed in 55ab0ce. Tested with manual pause only for now. I still need to perform real life tests when I get my bluetooth headset, but this should not pose any issue.

**Comment by grondinm** [comment]
Seems to work in either case. Thank you for this update and for otter in general
