### ISSUE TITLE
Allow playing all tracks of and artist.

### ISSUE THREAD

**Issue by JuniorJPDJ** [apognu/otter#21]
Hi,
I really lack this feature, I'd like to be able to add whole artist to queue.

PS. consider giving us a donation link :)

**Comment by apognu** [comment]
I will start working on this for the next release (1.0.18) of Otter. I still need to find a performant way to do this, but it should be OK.

As for donations, as explained in #18, I will only feel comfortable accepting them when I can find a way to contribute to Otter regularly. This is not the case yet (hence the few months without activity).

But thank you for your support. :)
