### ISSUE TITLE
Show albums and artists in search results

### ISSUE THREAD

**Issue by axelsimon** [apognu/otter#22]
Hi, thanks for your work on Otter, it's shaping up to be neat!

Currently, search results return all tracks that match the search term anywhere (artist, album, title) and shows them in what looks like a random list.

Having the results display, in order of importance:
- artists, then
- albums, then
- titles
sounds like a nice way to make that more helpful.

Or possibly, like Genius.com and Spotify do, show a title first if that really matches, and then artists and albums.

What do you think?

**Comment by apognu** [comment]
This should be implemented in fa82f13a9cf89ab3703f73dd5e85bdd7db2c660a, 98b2b31e205f38bcbfbe92cef1dc8aae61655b51 and 1038ee00ff7b837d06c313cf2cd196e12a948625 and will be available in 1.0.17.
