### ISSUE TITLE
Settings should have an "about" section

### ISSUE THREAD

**Issue by axelsimon** [apognu/otter#23]
There's a simple issue right now: how to tell which version of otter one is running?

The app doesn't say anywhere which version it is at, which isn't great if you want to see if you did remember to grab the latest `apk` from the github releases or not :wink: 

This is somewhat solved (or at least mitigated) by using Google Play (beh) or F-Droid (soon!), but in any case, an about section in the settings that would show the following would be useful, i think:
- version
- who's making this software
- the licence under which it is published
- the already existing "Open Source licences" section could also be moved here
- a link to the website /a link to Github to report issues

Do you agree?

**Comment by petitminion** [comment]
And a donation link o/

**Comment by apognu** [comment]
Hi!

Sorry about the delay.

Good idea. All the requested information now appears in the settings section. This is available in the latest version (1.0.16) which is currently being deployed to Google Play and availabel as an APK in the releases section.

As for donations, as explained in #18, and considering the personal issues that hinder me from dedicate fully to this project, I am not really comfortable accepting donations. Love the support, though, thanks!
