### ISSUE TITLE
HTTP Exception 405 Method not allowed

### ISSUE THREAD

**Issue by gnouts** [apognu/otter#3]
Hi,
I just tried to login and got an HTTP error : 405 Method Not Allowed.

My credentials are correct (as I used a password manager). I tried with my funkwhale password and not the subsonic API key.
I tried with and without the scheme `https://` in front of my domain.
Funkwhale is installed on the root of this domain.

I'm running v1.0.11 and my funkwhale server is still v0.19.0.

:)

**Comment by Brainwasher06** [comment]
Hello,

Same issue here, but i'm using Funkwhale v0.19.1

**Comment by EliotBerriot** [comment]
@Brainwasher06 right, I hade a look at the changelog, and the optional slash was introduced in https://dev.funkwhale.audio/funkwhale/funkwhale/commit/53b826c81a83a7f86cc3813cc45f4155ead92d62, so Funkwhale 0.20 and upward, I've updated my previous comment to reflect that

**Comment by apognu** [comment]
If all versions of Funkwhale handle the trailing slash, I will add it to all URLs to support as many instances as possible.

This should be available in the next update.

**Comment by apognu** [comment]
The update is being processed by Google and should fix this issue. I will close the issue when you can confirm it fixes everything on you side.

**Comment by apognu** [comment]
Good to hear. Enjoy and do not hesitate to open other issues if you find any. ;)
