### ISSUE TITLE
add track info and links

### ISSUE THREAD

**Issue by petitminion** [apognu/otter#30]
In the track playeur, Could be nice to see some info about the track as : 
- Url origin 
- Bit rate 

And some links :
- download track
- link to artist album (by clicking on artist name)
- link to tracks of album (by clicking on album name)

Thx a lot for your work ! The app is amazing o/

**Comment by apognu** [comment]
This commit should provide _most_ requested information. I did not implement track download, as this is a standalone feature that will be a bit more involved and I will implement separately.

**Comment by petitminion** [comment]
Thanks a lot ! :)
