### ISSUE TITLE
crash in lineage OS while scrolling

### ISSUE THREAD

**Issue by petitminion** [apognu/otter#32]
Using the app in a Samsung a5 with lineage os for micro g 16.0.

The crash appens when I scroll for artist, I enter the artist to see his album, I go back to artist list, I select another artist, and when I go back again, it crash.

I can provide some log if needed but I.don't know how :s

**Comment by apognu** [comment]
Hi!

I do not have a LineageOS phone at hand. But a very similar issue was fixed in 1.0.16, which was just release and is being deployed to the Play Store (and available here as an APK).

Could you try it whenever is convenient to you and report if your issue is fixed?

Thank you!

**Comment by petitminion** [comment]
Look like the new release fixe the issue ! 

Thx ! :)

**Comment by apognu** [comment]
Very good to know! Thank you for reporting.
