### ISSUE TITLE
Allow to filter own music

### ISSUE THREAD

**Issue by georgkrause** [apognu/otter#33]
When I open Otter, I get a hell of a lot of music which is federated from other pods. Some of them don't even have playable tracks. It would be nice if I could filter the results to show only my music.

**Comment by apognu** [comment]
Hi, thanks for reporting this.

How would you seen this control implemented? Could it be tucked under settings or does it need to be handy because you need to be able to switch it on and off often?

**Comment by apognu** [comment]
For reference, there seems to be a GET params, `scope` that changes to display one's own music vs. other's music : `scope=all` and `scope=me`.

**Comment by georgkrause** [comment]
I'd prefer to have a filter option available in the library view instead of an setting somewhere behind menus. But I could live with this option, too, if its easier.

**Comment by apognu** [comment]
It's mostly a UX issue. I'd like not to overwhelm the UI with options. Maybe I can add it to the main bottom bar overflow menu: easily accessible, but out of the way.

**Comment by georgkrause** [comment]
In case of the UI I would like to suggest a button next to the shuffle button in the album view:

![grafik](https://user-images.githubusercontent.com/939889/83790597-bb8c5f00-a698-11ea-8f18-68b9006dee53.png)

Maybe simply another button for "Download". 

In my case I would most likely make only full albums available in the device, but I guess in the song context menu might also be a good place:

![grafik](https://user-images.githubusercontent.com/939889/83790714-e70f4980-a698-11ea-8a10-44b5181c929e.png)

**Comment by apognu** [comment]
@georgkrause Did you write that comment on the wrong issue? This seems related to #37.

**Comment by georgkrause** [comment]
Yes, sorry for this. I like your idea.

If you can point me somewhere I could try to implement it

**Comment by apognu** [comment]
This should be implemented in d92e73cdabaef18d42ddd71a8be820ab265515c1. I'll merge into _develop_ when I have had the chance to test it a little. This requires Funkwhale 0.21+, since the `scope` parameter was added then, if I'm not mistaken.

This is how it looks like (easily available from every "browse" section).

<img src="https://user-images.githubusercontent.com/3017182/84575467-a69c8380-ad9c-11ea-9a15-66538353d0b6.jpg" width="200" />

**Comment by georgkrause** [comment]
Is there a way to get a apk of this version from CI for testing?

**Comment by apognu** [comment]
Not yet, but I should merge this branch tonight or tomorrow, and the build will then be available in the `tip` release.

I'll comment here when it is.

**Comment by apognu** [comment]
A debug build is now available [here](https://github.com/apognu/otter/releases/tag/tip). The feature is not behind the experimental flag yet, and will stay that way unless we notice some blocking issues.

You can reopen this issue if you want to continue discussing this feature (enhancements or bugs).

The build also contains the first preview for #37 (Offline downloading of tracks), which still needs some work, but is functional.
