### ISSUE TITLE
Library is empty after logging in

### ISSUE THREAD

**Issue by gisforgabriel** [apognu/otter#34]
I have successfully logged in to the app for the first time, but all menus are empty even after swiping down to refresh. The search system also fails to return any results.

Could this be because I am serving my Funkwhale instance at at subdomain and with a port? Maybe breaking some strings in the API calls? ie. `http://music.mydomain.com:3000`

I have the Subsonic API enabled and use Ultrasonic without a hitch, and the standard browser interface is also fine.

- Otter - latest Play Store version as of today
- Funkwhale - v0.20.1
- Android - v8.1.0

**Comment by apognu** [comment]
Hi,

I have seen a similar bug in _master_, but I do not think it was ever published in Google Play. Could you:

 * try again with the version released today (1.0.16), it may still be deploying on Google Play.
 * take a look at your Funkwhale logs to see if any error pops up when you use the app, or maybe publish some anonymized lines from it here?

Thank you.

**Comment by gisforgabriel** [comment]
Hi @apognu 
Thanks very much for taking time to push a new version. I tried and it didn't help. I also updated to Funkwhale 0.21 and that didn't help either.

But after upgrading to 0.21 all the album art stopped loading in the web interface, which got me thinking... My laziness in not setting up SSL (I'm the only user) meant I was getting content policy warnings. So I installed Caddy to add SSL and stop exposing the port number. That fixed the issue 🎉

I suspect it was probably the SSL alone which was causing the problem. Might be worth adding a line to the readme about it?

**Comment by apognu** [comment]
Indeed, as of now, SSL is required. What is weird is the login screen should is supposed to indicate this specific error condition whenever it happens.

I'll update the README and try and understand why the error did not show up for you anyway.

Thanks for reporting.
