### ISSUE TITLE
Shuffle mode in queue or songs

### ISSUE THREAD

**Issue by yiskah** [apognu/otter#35]
Maybe I just missed it but there doesn't seem to be an option for shuffling the queue, shuffling songs from an artist, or shuffling all tracks? Just shuffling favorites, playlists, and individual albums. I have experimental mode on and I'm on Android 9 on OnePlus 3. App from Google Play store don't see a version number anywhere.
![Screenshot_20200517-162450](https://user-images.githubusercontent.com/12243190/82159326-598bc700-985b-11ea-948a-0061b4bf8d7e.jpg)
![Screenshot_20200517-162517](https://user-images.githubusercontent.com/12243190/82159331-5e507b00-985b-11ea-86b2-7f9deff2386b.jpg)

**Comment by apognu** [comment]
You are right, these features are not yet implemented.

Playing/shuffling all tracks from an artist is mentionned by #21 and might be possible, as would be reshuffling of the queue.

On the other hand, I don't think playing all tracks will be considered for the moment, as this would entail loading all tracks (possibly throusands) into memory, shuffling them and loading them into the queue.

**Comment by apognu** [comment]
I'll close this issue in favor of #21, which covers it nicely.
