### ISSUE TITLE
App doesn't remove removed files

### ISSUE THREAD

**Issue by Thovi98** [apognu/otter#36]
First of all, thanks for this amazing app which already works great !

But I have found an issue : when I remove a music or an album server side, the app continues to show it, but says that it couldn't play the song (logically).

I think it would be fine to not show the removed music and make the app aware of the removal of the album/music.

Thanks 😃

**Comment by apognu** [comment]
Thanks for your support.

Does this happen even if you pull to refresh (in order to bypass your cache)?

**Comment by Thovi98** [comment]
Yes, I have deleted data of the app to resolve this issue. But later I removed a new song, and it removed from the app too, so it’s maybe in some particular cases that the issue appears. 

It appeared when I removed all my songs, so my Funkwhale was empty (because I renewed my database). Maybe is this fact not planned by the app ?

So it’s not a big issue, because there are other ways to resolve it (deleting data), and it appaers not in all cases. 

Thanks for this app and for last update, I like it very much.

**Comment by apognu** [comment]
I really can't seem to reproduce this.

If I delete a track from my instance, on the next sync (by forcing it by pull to refresh), the item disappears from Otter.

Could you elaborate on the steps necessary to reproduce this issue?

**Comment by Thovi98** [comment]
No sorry, I can’t reproduce this too anymore. When I delete a track from my instance, it disappears from Otter too. 

Maybe it’s because of that I removed the entire library ? But in this case it’s not a problem to remove all data of the app manually.

But sorry, I can’t reproduce.

Thanks again for your amazing work, I like it very much !!

**Comment by apognu** [comment]
No problem. I'm glad this is fixed for you.

I'll close this issue, do not hesitate to reopen if this happens to you again.

Thanks for the support!
