### ISSUE TITLE
Wrong passwords are not trapped (400, login)

### ISSUE THREAD

**Issue by parnikkapore** [apognu/otter#4]
Entering a wrong password makes the server field turn red and say "Exception 400: Bad request" - obviously very confusing to someone who hasn't read the Funkwhale API docs.

Suggested fix: Check for a "wrong password" condition, and add a separate error message.

**Comment by apognu** [comment]
This is actually on the roadmap, but is not prioritized right now. I will get onto UX improvements later. Thanks for reporting, will keep this issue open until this is fixed.

**Comment by apognu** [comment]
We are now displaying error messages from the API on failed login. This landed in 40117122c701b88ba0b32b50ff6e0ea0b757b8b6 and will be included in 1.0.16.

**Comment by apognu** [comment]
This should be fixed in 1.0.16, which is being deployed to Google Play as we speak and available as an APK in the releases section.
