### ISSUE TITLE
Otter crashes instantly

### ISSUE THREAD

**Issue by dani** [apognu/otter#45]
Just installed the update from Google play, Otter can't be starter anymore, it's closed instantly. Running Android 10

**Comment by dani** [comment]
It's against a 0.21.1 Funkwhale server

**Comment by apognu** [comment]
Can you try and fetch some logs from ADB?

Also, did you try installing it from scratch? Completely uninstalling it and reinstalling it, or clearing storage?

**Comment by apognu** [comment]
Also, there is a new version (1.0.19) being reviewed right now by Google that fixes an issue at launch, it should be available in a few hours.

Tell me if the issue still appears after that update.

**Comment by dani** [comment]
Clearing the app data fixed it. I've submited crash logs through the Google helper launched after the crash (not sure if you receive it)

**Comment by apognu** [comment]
Good thing that it fixed it for you!

Thanks for the report. It can take a long time for them to show up in the Play Console (sometimes up to 24 hours). I'll give it a look then and see what I can do.

Closing for now, I'll reopen if I get the report and see something unexpected.
