### ISSUE TITLE
add volume management in setting

### ISSUE THREAD

**Issue by petitminion** [apognu/otter#46]
Hey !

Could be nice to add an option in the setting to control audio volume (increase or decrease default dB). 
That way people could manage their peculiar devices (more dB with headphone, less with earphone) when the phone is too loud or not enought.

For exempla vanilla music player as su,h option in sttings, audio, replay gain.

Hope this is clear haha

**Comment by apognu** [comment]
Otter does not influence audio playback, except for interfaces provided by ExoPlayer (this goes for supported codecs, audio normalization, etc.). So, if ExoPlayer does not support specific audio processor, this is not something we will be able to add.

I'll have a look around ExoPlayer anyway, to check if they do support something like this, but it does not ring a bell.

**Comment by keunes** [comment]
From what I (think to) know from AntennaPod, the options wirh ExoPlayer are limited.

**Comment by apognu** [comment]
That's what I figured from my small attempts at research. I'll keep this open while I finish my due diligence in studying ExoPlayer, but this may end up as a wontfix if nothing comes up.

**Comment by apognu** [comment]
Adding `wontfix` label for now, and will be closed in some time if I don't find any way to do that.
