### ISSUE TITLE
Otter crashes when "Playing next" on an empty queue

### ISSUE THREAD

**Issue by apognu** [apognu/otter#48]
**Describe the bug**

When the queue is empty (usually on the first run of the app), clicking on "Play next" crashes the app.

No issue when the queue contains tracks.

**How to reproduce**

1. Start the app for the first time
2. Go to an album view
3. Click on "Play next" for a track
4. Otter crashes

**Expected behavior**

Otter should not crash, but add the track as the first item in the queue.

**Comment by keunes** [comment]
> **Expected behavior**
> 
> Otter should not crash, but add the track as the first item in the queue.

If the queue doesn't contain a track, shouldn't that be 'respected'? If the queue is empty and you want to 'fill' the queue, which track would be added then?

**Comment by apognu** [comment]
The "Play next" button is in the context of a specific track, so my guess would be this specific track should be added to the queue.

It makes sense to me that when instructing to play a track next, this track would be the first thing that plays when starting playback. Did you have something else in mind?

I could not reproduce the issue this morning, so I'll have to dig a bit deeper.
