### ISSUE TITLE
Allow Anonymous Instance Connections

### ISSUE THREAD

**Issue by dregin** [apognu/otter#49]
My Funkwhale instance allows anonymous API requests.

Instead of giving people accounts, I'd like them to be able to use otter to connect to the instance anonymously.

**Comment by apognu** [comment]
The login screen should already have an "anonymous authentication" checkbox since resolution of #14. Is this not working for you?

**Comment by dregin** [comment]
Ah, I'd not logged out in a while. This option wasn't there before. Thanks.
