### ISSUE TITLE
Refuses to play music when cache size set to 0

### ISSUE THREAD

**Issue by parnikkapore** [apognu/otter#5]
Set the cache size to 0GB. Then try to play something. The audio player would seem to hang.

Suggested fix: This would most likely require an overhaul. Alternatively, alias "0GB" to something like 50MB.

**Comment by apognu** [comment]
This is indeed a bug. I'll try and lift this strange limitation, media playback should not have issue if cache is disabled.

I would prefer not to sweep it under the rug if possible. But if I can't find a solution, I could set a minimal cache value.

**Comment by apognu** [comment]
I can't seem to reproduce this. Are you able to reproduce it on all your tracks?

**Comment by parnikkapore** [comment]
Also irreproducible here. I'll close it for now, and look for some unstable connection UI lags 😗
