### ISSUE TITLE
Add new content filter for subscribed libraries

### ISSUE THREAD

**Issue by apognu** [apognu/otter#52]
As of now, Otter supports filtering content owned by the logged in user. We could enhance this filter by also having one for content included in libraries the user is subscribed to.

This filters UI would need to be revamped (right now, it is a simple checkbox) to allow for multiple filters to be selected.

Finally, it requires some changes on Funkwhale's side that are tracked in [this issue](https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1116).

**Comment by georgkrause** [comment]
`Can now filter subscribed content through API (#1116)`

Since funkwhale 0.21.2 thats implemented :)

**Comment by apognu** [comment]
I've started working on this.

The UI is almost done, but I'm still having some difficulties making the `subscribed` scope work as advertised.

But, progress.

**Comment by apognu** [comment]
Funkwhale had to fix an issue in the implementation for this filter, but here we are: content filters are implemented in develop!

<img src="https://user-images.githubusercontent.com/3017182/92166383-d22d8800-ee38-11ea-929c-c1b51015bd4d.png" width="300" />
