### ISSUE TITLE
Metadata unknown on ambient screen when using radio

### ISSUE THREAD

**Issue by benferreri** [apognu/otter#55]
Normally, when playing a track, the title and artist are shown on the ambient display lock screen (I'm on OxygenOS; not sure if this is a thing for all Android 10 variants). When playing a track from a radio, though, it displays the track title as 'Unknow' and the artist as 'Unknown artist'.

**How to reproduce**

1. play a radio
2. lock device and tap screen to turn on ambient display
4. see unknown metadata

**Expected behavior**

Track title and artist name should be displayed.

**Screen recording**
The [streamable link here](https://streamable.com/m2m65n) shows:
1. playing a track directly from an album
2. locking the screen and showing the ambient display; at the bottom, the track title and artist are shown
3. playing a random track from radio
4. locking the screen and showing the ambient display; at the bottom, 'Unknow' and 'Unknown artist' are shown
5. finding the random track from a search and playing it directly from the album
6. locking the screen and showing the ambient display; at the bottom, the correct information is shown. this was mainly to demonstrate that it is not dependent on track and is instead dependent on using the radio.

**Environment details**

 - Device: OnePlus 7T
 - Android version: OxygenOS / Android 10
 - App version: 1.0.19

**Comment by apognu** [comment]
Thank you for the detailed report.

Apparently, the ambient display is correctly set but almost immediately overriden by something (probably ExoPlayer). I think I have a lead to fix this. I'll keep you posted.

**Comment by apognu** [comment]
I found the a way.

Other than ambient display, it did impact media controls on watches and probably on some other devices.

This will be a larger fix that reshapes the way media metadata is exposed. If I am able to test most of the usual use cases, we should have a more coherent result across devices.
