### ISSUE TITLE
Empty library after logging in through HTTP

### ISSUE THREAD

**Issue by HeiWiper** [apognu/otter#56]
**Describe the bug**

The library is empty after successfully logging in through HTTP, it seems just like the bug reported on #34, I tried to use other subsonic music players to make sure it's not an instance issue and the tracks were loaded just fine.

**How to reproduce**

1. Login through HTTP local IP (http://192.168.x.x:x)
2. Check Allow cleartext traffic (HTTP)
3. Click on LOG IN button

**Expected behavior**

Loading the tracks from the library.

**Screenshots**

![image](https://user-images.githubusercontent.com/12894695/86912519-0fb1b580-c115-11ea-8344-cb2aef39bcee.png)

**Environment details**

 - Device: Moto G6
 - Android version: 10 (Custom ROM)
 - App version: 1.0.20
 - If public Funkwhale instance, its URL: Local instance version 0.21.1

**Logs**

No crash logs.

**Comment by apognu** [comment]
That's my bad, I forgot one place where I enforced HTTPS. I'm really sorry about that. This will be fixed as soon as possible and I hope I'll be able to deploy a fix this week.

**Comment by apognu** [comment]
de0a494b436521596cc8df1cdcf310def4ff8338 shoud fix this issue.

Would you mind testing the latest [tip release](https://github.com/apognu/otter/releases/tip) and report back?

**Comment by HeiWiper** [comment]
The tip release seems to fix it, everything is working fine now thank you so much ~
I don't know if this is related but the covers didn't show up it's just blank

**Comment by HeiWiper** [comment]
Apparently it's related to my instance never mind and thank you again !
