### ISSUE TITLE
Add possibility to clear the queue

### ISSUE THREAD

**Issue by MightyCreak** [apognu/otter#66]
Right now it doesn't seem possible to clear the Otter tracks queue.

It would be nice to have such options in the queue UI. It would allow to manage your queue, that could become cluttered sometime.

Also, since this would mean to rethink the queue layout (i.e. it would not just be a track list any more), it could be a good occasion to think about other queue features like shuffle, track reordering, etc...

**Comment by apognu** [comment]
For what it's worth, reordering of queue item is already possible by dragging the handle on the left of it.

I could see the need to clear and (re-)shuffle it, we'd just need to be clear on the behavior of those features.

> Also, since this would mean to rethink the queue layout (i.e. it would not just be a track list any more)

What did you have in mind by that?

**Comment by MightyCreak** [comment]
> What did you have in mind by that?

Just that right now it is a track list and by adding new features like clear and shuffle, it would make the UI a bit more complex. That said, shuffle was but an idea, I'm not even sure I would use it personally.

But I will definitely use the "clear tracklist" feature. Otherwise I get like 200 tracks is in my tracklist and it just keeps getting bigger and bigger.

**Comment by gisforgabriel** [comment]
I agree with @MightyCreak - some method of clearing the queue would be very useful. It's very easy to bulk add large albums, but items have to be removed individually.

I'm no UI expect so I wouldn't mind what form this takes, but I was thinking an easy addition might be: long press on the queue icon in the footer opens an option to clear (this might interfere with the short press label function though)?

**Comment by apognu** [comment]
I agree with the addition of a button to clear the queue, though it will not be hidden away behind a long press. I really hate this idiom for being difficult to discover and not really accessible.

So it will have to go through some UI refactoring. :)

For the time being, queue **can** be cleared through the Shuffle action or pressing a trsck in any album.

**Comment by gisforgabriel** [comment]
> I really hate this idiom for being difficult to discover and not really accessible.

Me too to be honest. I was just thought it might be a quicker patch than, for example 😉:
> So it will have to go through some UI refactoring. :)

> For the time being, queue **can** be cleared through the Shuffle action or pressing a trsck in any album.

I had never noticed that. That's more than good enough for me as it is for now 👍. Thanks for the super quick reply

**Comment by apognu** [comment]
UI-wise, this would look something like that (clear + shuffle).

Implementation has also started (not finished and there are still bugs).

<img src="https://user-images.githubusercontent.com/3017182/91885218-b2a32d80-ec87-11ea-847a-49ebada10f4d.png" width="500">
