### ISSUE TITLE
Give some appreciation to @apognu

### ISSUE THREAD

**Issue by phpwutz** [apognu/otter#67]
Hey there!
I'm using Otter since about half a year backed by my self-hosted funkwhale instance.
Just wanted to throw a quick message of appreciation over the fence (alongside with some german translation suggestions, which are on weblate) .
Otter finally enables the community to have a reasonable self-hosted music setup (playcount, any other setup?), for which I am very greatful.
I know it can be hard sometimes to maintain open source projects, when every other issue seems to be screaming "moar features!". While it's obvious that there are lots of possibilities to improve Otter, I'm not an Android developer, so instead I'd like to say

**Thank you a thousand times for creating and open sourcing this!**

I wish you and your loved ones all the best, keep up the great work and may your efforts be repaid.

**Comment by apognu** [comment]
Hi @phpwutz,

Thanks a lot for the kind words, I am really glad Otter can be of use to some of you. :)

> I know it can be hard sometimes to maintain open source projects, when every other issue seems to be screaming "moar features!".

People wanting more features is not really an issue per se, I welcome it. This community is pretty benevolent, and understands not everything can be done. So those are pretty nice conditions as far open source software is concerned.
