### ISSUE TITLE
Keep downloaded tracks on log out

### ISSUE THREAD

**Issue by apognu** [apognu/otter#68]
Currently, all data is deleted on log out. This can be very problematic if you get disconnected because of a transient issue with Otter or the upstream instance.

Moreover, Funkwhale is changing the way app must authenticate to it, which means we may be logged out during the process when the change comes. This could prevent losing one's downloaded tracks when it happens.

The first version of this will be very naive, always keeping downloaded tracks in persistent storage. We may want to think about something more clever later, like deleting downloaded tracks from instance A if we connect to instance B, or something like that.

**Comment by keunes** [comment]
Are you blazing fast fixing this or did you change your mind @apognu ? :)

**Comment by apognu** [comment]
Haha, that really was only one deleted line, so in this case, I was fast.
