### ISSUE TITLE
Wrong order of tracks in an album

### ISSUE THREAD

**Issue by Atilir** [apognu/otter#73]
Hi,

The problem https://github.com/apognu/otter/issues/13 as reappeared but this time it is not random but it inversed the order of tracks. 

I updated otter to 1.0.20 and updated my funkwhale instance to 0.21.2. I don't know if this caused any issue.

Thanks.

**Comment by apognu** [comment]
Does anyone have the same issue? I cannot reproduce this, album tracks should be sorted by track `position`.

**Comment by AMoonRabbit** [comment]
I have similar issues, a lot of my albums are not in the correct order. Not sure whether this is a Funkwhale ID problem as I know tracks don't upload in order either, and they are all assigned IDs in Django. Screenshot of one multi disk album which for some reason starts halfway through the album. https://musicbrainz.org/release/b0f090a6-e333-4620-98d9-f57d959dcb79 for the actual track order. 

First disc as is on my Funkwhale instance:
![image](https://user-images.githubusercontent.com/3766988/91725963-5bbe2b00-eb97-11ea-9ba1-964d253fc569.png)

Other albums however, do appear in order. Truly an odd one. Is there anything else we can provide to support this issues resolution?
![Screenshot_20200831-140256](https://user-images.githubusercontent.com/3766988/91722901-d89ad600-eb92-11ea-8c3a-cd02ea98e424.png)

**Comment by apognu** [comment]
Could you report something for me?

Can you play the first shown track of this album in Otter and display the track information (overflow menu of the `Now Playing view > Information)`. The `Album position` value is what would be interesting to me.

**Comment by AMoonRabbit** [comment]
Morning.

As requested, please see the below track information 

![Screenshot_20200901-110158](https://user-images.githubusercontent.com/3766988/91836482-be203580-ec42-11ea-8536-18c4382c3280.png)

**Comment by AMoonRabbit** [comment]
Also just finding the first track of the first volume or disc, I noted that despite the album listing beginning with track 6, further down the track list all of the 1st tracks are bunched together, then all the 2nd tracks etc. So it looks like for this album, it's started with all tracks with position 6 through to 19 and then restarted at 1 midway through. Really bizarre ordering. But I note that's no disc counter either so that would also be an issue?

**Comment by tigresansrayure** [comment]
I have the same issue with a 2 discs album.
Ordering is good in Funkwhale 0.21.1, while in Otter 1.0.21 the tracks are ordered as followed :

- Disc 2 - Track 1
- Disc 1 - Track 1
- Disc 1 - Track 2
- Disk 2 - Track 2
- Disk 1 - Track 3
- Disk 2 - Track 3
- Disc 2 - Track 4
- Disc 1 - Track 4
- etc.

**Comment by apognu** [comment]
@tigresansrayure That is helpful, I have no notion of "disc number", so it would make sense the ordering would present like that.

But I'm not sure it applies to @Atilir's and @Razgriz375's issues, does it?

I'll go check if Funkwhale publishes this disc number in its API, if so, it should be quite easy to include this in next's update.

**Comment by AMoonRabbit** [comment]
Disc numbers does has a factor in my issue as it's a 4 disc release,
however, still not sure why it started with track 6 rather than track 1.

**Comment by tigresansrayure** [comment]
@apognu Looking at what I believe is the track ID (using the number for each track in its URL, domain/tracks/<ID>), I think it provides more interesting information (at least in my case) : the ordering seems to follow first the track number (regardless of disc number), then the track ID (in DESC order).
In my case :

- Disc 2 - Track 1 - ID 2675
- Disc 1 - Track 1 - ID 2664
- Disc 1 - Track 2 - ID 2665
- Disc 2 - Track 2 - ID 2656
- Disc 1 - Track 3 - ID 2666
- Disc 2 - Track 3 - ID 2657
- Disc 2 - Track 4 - ID 2667
- Disc 1 - Track 4 - ID 2658

And so on.

Hope that helps and is also relevant to @Razgriz375 issue.

**Comment by apognu** [comment]
Are you all on public instances? If so, could you send me a link to one of those album so I can debug it properly (I have no multi-disc albums in my library).

If not, I'm sure I can find one of those quite easily on open.audio.

Thank you!

**Comment by AMoonRabbit** [comment]
Okay, @tigresansrayure thanks for the suggestion on the Django ID's, I have taken some time to right the ID's and then enter them into this spreadsheet for the album I have: https://docs.google.com/spreadsheets/d/1qOLDGYlNLtsVXo84F9jI1irxzl2S31B4S0ghoFtULfQ/edit?usp=sharing

Now the only thing I haven't done with this document is put the true track numbers in, but sorting by either Django ID, or Mbid does not give me the order that the app is producing still. 

Edit: Added the actual track numbers, but Sheets doesn't let me filter by 2 columns at once.

**Comment by AMoonRabbit** [comment]
@apognu I've made mine public for the moment. You can just search Ace Combat 5. Can you let me know when you're done. http://music.amoonrabbit.reisen/federation/music/libraries/767f2b22-e040-4ceb-a913-5df8d636ae66

**Comment by apognu** [comment]
Thanks!

If you do not want to keep it open for too long, I can create an account now so you can close the gates again. You'll be able to delete the account once I'm done reproducing (tonight GMT).

**Comment by apognu** [comment]
But I can see from your API that Funkwhale sorts the tracks by `disc_number,position`, which Otter does not.

So a change with that will improve things altogether, but I'd still like to be abe to test it first hand. :D

**Comment by AMoonRabbit** [comment]
Would that also explain why it's starting with track 6 instead of track 1? I don't mind if you create an account, equally don't mind leaving it open until it's resolved.

**Comment by apognu** [comment]
OK, so I've found the issue.

There was three separate (but related) problems:
 * I obviously missed something as I was lacking the proper options to have Funkwhale sort the overall response (this was really a mistake on my part).
 * I was not aware of the `disc_number` attribute (did not even consider albums made of several discs).
 * For such large albums, the track list comes in several requests, and I was sorting each individually (which, without upstream sorting, rendered this weird and inconsistent sorting order). Hence this example with the first track being at position 6, it was actually the smallest `position` within the first request.

I am going to clean up my fix and push this on the `develop` branch for you to test (if it is possible for you to install the dev version alongside your production one, they should coexist side by side). I'll wait for you three (@Atilir @Razgriz375 and @tigresansrayure) to confirm whether or not it fixes your respective issues before closing.

**Comment by AMoonRabbit** [comment]
I've installed the latest tip release, and can confirm I am seeing the fix and correct behaviour (though it did weirdly duplicate the last disc at first but a refresh of the album resolved that). So I'm happy. Just need the others to confirm.

**Comment by tigresansrayure** [comment]
Just come home, nice to see you seem to have found a fix ! 😃 
Although I don't know how to test this, as I am just using Google Play Store and it's not showing any update yet. I don't know how to install the "latest tip release" as @Razgriz375 did.

**Comment by apognu** [comment]
@tigresansrayure : Sorry about that. The bleeding-edge version of Otter is continuously built and always available [in the APK listed here]( https://github.com/apognu/otter/releases/tag/tip).

This version does not replace the production version of Otter, but is literally a "second Otter" on your phone that can be used to test the latest features and fixes.

This fix, if confirmed should be promoted to the Play Store in a week or two, depending on what other features or fix can be merged together.

**Comment by AMoonRabbit** [comment]
@tigresansrayure You will need to allow either Files or your browser to install apps from untrusted sources. Your phone should take you to the option when you attempt to run the downloaded file.  You will then have Otter (develop) in your app drawer if successful.

**Comment by tigresansrayure** [comment]
Thank you both.
Installed, and tested : track ordered as expected !
I'm OK with this fix.

**Comment by apognu** [comment]
OK thank you a lot!

Let's wait a bit for @Atilir (it was his original issue after all), and we'll close this if they confirm as well.

**Comment by Atilir** [comment]
Sorry for the late response ....

It's good for me with the dev version

**Comment by dnno** [comment]
Hi! I still see order inconsistencies, see screenshot attached. Let me know if I can provide more details...

<img width="586" alt="screenshot1" src="https://user-images.githubusercontent.com/2003552/102710591-8dc4db80-42b3-11eb-8d9d-f04052205fcb.png">

<img width="693" alt="screenshot2" src="https://user-images.githubusercontent.com/2003552/102710609-b51ba880-42b3-11eb-8847-5f0e2aaa4ad4.png">

**Comment by AMoonRabbit** [comment]
Have you refreshed that album? To me it looks like it hasn't indexed the missing tracks at all yet.
