### ISSUE TITLE
Shuffle and Clear buttons do nothing when in landscape orientation

### ISSUE THREAD

**Issue by AMoonRabbit** [apognu/otter#76]
**Describe the bug**

When Otter is in landscape orientation, the options for Shuffle and Clear on the playlists section (on the right) no longer function beyond cosmetically. Therefore, you cannot clear the queue or reshuffle the queue in this orientation

**How to reproduce**

1. Enable screen rotation
2. Use Otter and play a radio or something else
3. Rotate phone so that it is in landscape, and Otter changes to accommodate this
4. Try to clear the queue or shuffle the queue via the available options at the top of the list.

**Expected behavior**

The buttons should function as they do when you are using Otter in the portrait orientation.

**Environment details**

 - Device: Pixel 4
 - Android version: 11
 - App version: 1.0.21-3-50c8dac-develop
 - If public Funkwhale instance, its URL: music.amoonrabbit.reisen (there is one album available publicly if needed.

**Comment by apognu** [comment]
This should be fixed in the next `develop` build. Simply forgot to implement the behavior for landscape.

Thanks!
