### ISSUE TITLE
Album ordering scatter based on letter case

### ISSUE THREAD

**Issue by AMoonRabbit** [apognu/otter#80]
**Describe the bug**

It appears that the Albums, and possibly other sections, aren't ordering quite how you'd expect. I'm seeing all CAPS album names A-Z before Normal Albums, and the lowercase albums at the end of the list. Whether this is case sensitive issue or something else behind the scenes will need further investigation.

**How to reproduce**

View the order of albums

**Expected behavior**

Assuming the default ordering is alphabetical, then regardless of case, albums should be ordered correctly. 

**Screenshots**

![Screenshot_20200906-134146](https://user-images.githubusercontent.com/3766988/92326128-af24f300-f047-11ea-80a6-9bf1c88fde01.png)
![Screenshot_20200906-134154](https://user-images.githubusercontent.com/3766988/92326131-b77d2e00-f047-11ea-9a3a-5b4c26247c98.png)
![Screenshot_20200906-134218](https://user-images.githubusercontent.com/3766988/92326136-c06dff80-f047-11ea-94c9-a816be337e7f.png)
![Screenshot_20200906-134424](https://user-images.githubusercontent.com/3766988/92326137-c237c300-f047-11ea-934b-1bf06428207d.png)

**Environment details**

 - Device: Pixel 4
 - Android version: 11
 - App version: 1.0.21-3-50c8dac-develop
 - If public Funkwhale instance, its URL:

**Comment by apognu** [comment]
Thanks for opening this.

As discussed on Matrix, I cannot seem to reproduce this on open.audio or my own instance. Awaiting access to your private instance to try and debug this.

**Comment by AMoonRabbit** [comment]
This has been confirmed to be on my pod's end and not app specific. Closing issue.
