### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by mariof1** [apognu/otter#9]
Hi,
Great project!
Would you consider implementing landscape mode? 
I listen to music mainly on the road on Android head unit which only operates in landscape mode.

**Comment by apognu** [comment]
This is something I would like to do as well, but I honestly, for now, swept it under the rug to focus on core functionality.

I have a rough idea of what it could look like (browsing on the left, current queue on the right), but I'll still have to implement this as well as managing rotation gracefully.

Good thing is this could also be out tablet layout.

I'll keep this issue updated when I can begin working on it.

**Comment by apognu** [comment]
This is what I had in mind. This is a really early attempt, lots of things are buggy, and unadapted to landscape (cover art headers should be removed, for example).

Is that something you would be happy with?

![Screenshot_20191105-203351](https://user-images.githubusercontent.com/3017182/68239815-9ac93180-0003-11ea-820d-624c6fae1a92.jpg)

![image](https://user-images.githubusercontent.com/3017182/68240132-3a86bf80-0004-11ea-9960-d1f356026b30.png)

![image](https://user-images.githubusercontent.com/3017182/68240149-3f4b7380-0004-11ea-89a3-24508ee5dab5.png)

**Comment by mariof1** [comment]
Yeah, I think that should do for the begging. I understand this is still very early stage so once it is implemented let users test it and see if they find ant bugs.

**Comment by apognu** [comment]
Preliminary implementation landed in 40117122c701b88ba0b32b50ff6e0ea0b757b8b6, and will be included in version 1.0.16.

**Comment by axelsimon** [comment]
I think a Github label `in progress` would help to see this is happening, at a glance :)

**Comment by apognu** [comment]
Hi,

Sorry about the delay.

This first implementation is now available in 1.0.16, which is being deployed in Google Play and available as an APK here.

Please open a separate issue if you have any idea on how this could be enhanced.
